services:
  php:
    build: ./backend
    container_name: evenements_php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: evenements_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evenements
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
